### ISSUE TITLE
Incompatibility with either phpBB 3.3.8 or PHP 8.0

### ISSUE THREAD

**Issue by afalkenhahn** [pierrdu/lmdi_autolinks#5]
I've updated from phpBB 3.3.0 to 3.3.8 and my hoster has updated from PHP 7.4 to 8.0. When I go to the ACP and select "Autolink configuration", the following errors show up:

```
[phpBB Debug] PHP Warning: in file [ROOT]/ext/lmdi/autolinks/acp/autolinks_module.php on line 268: Undefined variable $sort_col
[phpBB Debug] PHP Warning: in file [ROOT]/ext/lmdi/autolinks/acp/autolinks_module.php on line 274: Undefined variable $sort_order
[phpBB Debug] PHP Warning: in file [ROOT]/ext/lmdi/autolinks/acp/autolinks_module.php on line 328: Undefined variable $th_term
[phpBB Debug] PHP Warning: in file [ROOT]/ext/lmdi/autolinks/acp/autolinks_module.php on line 329: Undefined variable $th_url
[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions_acp.php on line 139: Cannot modify header information - headers already sent by (output started at [ROOT]/includes/functions.php:3027)
[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions_acp.php on line 139: Cannot modify header information - headers already sent by (output started at [ROOT]/includes/functions.php:3027)
[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions_acp.php on line 139: Cannot modify header information - headers already sent by (output started at [ROOT]/includes/functions.php:3027)
[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions_acp.php on line 139: Cannot modify header information - headers already sent by (output started at [ROOT]/includes/functions.php:3027)
```

Would be nice to have a fix for this.

**Comment by pierrdu** [comment]
For the time being, I'm switching my development computer. I'll come back in a few hours.

**Comment by pierrdu** [comment]
Well, those variables are correctly declared and the extension works fine on my test server. Did you use the latest version or some older one?

**Comment by afalkenhahn** [comment]
Yes, latest version but recently updated. Before I switched to phpBB 3.3.8 and PHP 8.0 I was using version 1.3.3 from 2020/05/15. But when I got the error quoted above, I updated to the latest version from this repository yesterday but the error still wouldn't go away. Autolinks still works but that error message in the ACP is somewhat annoying so would be nice to get rid of it...

**Comment by pierrdu** [comment]
I'll test tomorrow with PHP 8.

**Comment by pierrdu** [comment]
Same thing with php 8.1. The cause must lie somewhere else.

**Comment by afalkenhahn** [comment]
`sort_col` and `sort_order` are initialized here:

```
		$sort = $config['lmdi_autolinks_sort'];
		switch ($sort)
		{
			case 0 :
				$sort_col = 0;
				$sort_order = 0;
				break;
			case 1 :
				$sort_col = 0;
				$sort_order = 1;
				break;
			case 2 :
				$sort_col = 1;
				$sort_order = 0;
				break;
			case 3 :
				$sort_col = 1;
				$sort_order = 1;
				break;
		}
```

Could it be that `$config['lmdi_autolinks_sort']` is a value that is not >= 0 && <= 3 so that `sort_col` and `sort_order` aren't initialized? How can I check what the value of `$config['lmdi_autolinks_sort']` is?

**Comment by pierrdu** [comment]
Good idea.
The data is stored in the phpbb(3)_config table, under the key lmdi_autolinks_sort. Maybe should I add a default case to the zero case.

**Comment by afalkenhahn** [comment]
For some reason this key doesn't exist in my `phpbb_config` table. The only keys related to lmdi_autolinks are those two:

```
('lmdi_autolinks', '2', 0),
('lmdi_autolinks_blank', '1', 0);
```

So that explains the error. But I don't understand why the error didn't occur when I still was on phpBB 3.3.0 and PHP 7.4.

**Comment by pierrdu** [comment]
Thanks for this pointer. I'll definitvely add a default in the switch.

**Comment by afalkenhahn** [comment]
Thanks, but you also need to do add it here:

```
		switch ($al_sort)
		{
			default:
			case 0 :
				$th_term = '&amp;action=sort&amp;col=0&amp;order=1';
				$th_url  = '&amp;action=sort&amp;col=1&amp;order=0';
				break;
			case 1 :
				$th_term = '&amp;action=sort&amp;col=0&amp;order=0';
				$th_url  = '&amp;action=sort&amp;col=1&amp;order=0';
				break;
			case 2 :
				$th_term = '&amp;action=sort&amp;col=0&amp;order=0';
				$th_url  = '&amp;action=sort&amp;col=1&amp;order=1';
				break;
			case 3 :
				$th_term = '&amp;action=sort&amp;col=0&amp;order=0';
				$th_url  = '&amp;action=sort&amp;col=1&amp;order=0';
				break;
		}
```

Otherwise there'll be warnings that `th_term` and `th_url` are uninitialized... (see error message in OP)

**Comment by pierrdu** [comment]
Done. Thanks.
